version: '3.4'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: password
           MYSQL_DATABASE: rails-db
           MYSQL_USER: user
           MYSQL_PASSWORD: userpassword
    app1: 
        build:
          dockerfile: dockerfile
        depends_on:
            - db
        volumes:
            - ./storage:/app/storage    
    app2: 
        build:
          dockerfile: dockerfile
        depends_on:
            - db
        volumes:
            - ./storage:/app/storage     
    app3: 
        build:
          dockerfile: dockerfile
        depends_on:
            - db
        volumes:
            - ./storage:/app/storage                     
    proxy:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"    
        depends_on:
            - app1
            - app2
            - app3 

