apiVersion: v1
kind: Service
metadata:
  name: app-net
spec:
  replicas: 3
  selector:
    app: app
  ports:
    protocol: TCP
    port: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: w453y/rails-app:latest
        ports:
        - containerPort: 3000
          protocol: TCP  
